use std::{path::Path, process::Command};
use crate::{config::{app_config::AppConfig, ssh_config::{default_ssh_config_path, parse_default_ssh_config}}, ssh::host::SshHost};
#[derive(Debug, Clone, Default)] pub struct HealthInfo { pub uptime:String, pub kernel:String, pub memory:String, pub disk:String, pub failed_services:u32, pub docker_containers:u32 }
impl HealthInfo { pub fn empty() -> Self { Self { uptime:"unknown".into(), kernel:"unknown".into(), memory:"unknown".into(), disk:"unknown".into(), failed_services:0, docker_containers:0 } } }
pub struct DoctorReport { checks: Vec<(String,bool,String)> }
fn exists(bin:&str)->bool{ Command::new("sh").arg("-c").arg(format!("command -v {bin} >/dev/null 2>&1")).status().map(|s|s.success()).unwrap_or(false) }
impl DoctorReport { pub fn run(cfg:&AppConfig)->Self{ let mut c=Vec::new(); c.push(("ssh binary".into(), exists("ssh"), "required for connections".into())); c.push(("scp binary".into(), exists("scp"), "required for transfers".into())); c.push(("sftp binary".into(), exists("sftp"), "required for batch SFTP".into())); let ssh_cfg=default_ssh_config_path(); c.push(("~/.ssh/config".into(), ssh_cfg.as_ref().is_some_and(|p|p.exists()), "missing is OK; add hosts in SSHDeck".into())); let parsed=parse_default_ssh_config(); c.push(("SSH config parse".into(), parsed.is_ok(), parsed.as_ref().map(|h|format!("{} host(s)",h.len())).unwrap_or_else(|e|e.to_string()))); c.push(("managed config path".into(), cfg.path.parent().is_some_and(Path::exists), cfg.path.display().to_string())); if let Some(home)=dirs::home_dir(){ let ssh=home.join(".ssh"); c.push(("~/.ssh permissions".into(), ssh.exists(), ssh.display().to_string())); } for h in parsed.unwrap_or_default(){ if let Some(k)=h.identity_file { c.push((format!("key for {}", h.alias), k.exists(), k.display().to_string())); }} c.push(("unicode setting".into(), cfg.ui.unicode, format!("nerd_font={}", cfg.ui.nerd_font))); c.push(("default local files dir".into(), expand_tilde(&cfg.files.default_local_dir).exists(), cfg.files.default_local_dir.clone())); Self{checks:c} } pub fn render_text(&self)->String{ let mut s=String::from("SSHDeck doctor

"); for (name,ok,detail) in &self.checks { s.push_str(&format!("{} {:28} {}
", if *ok {"✓"} else {"⚠"}, name, detail)); } s } }
fn expand_tilde(p:&str)->std::path::PathBuf{ if let Some(rest)=p.strip_prefix("~/"){ dirs::home_dir().unwrap_or_default().join(rest) } else { p.into() } }
pub fn health_commands() -> [&'static str; 6] { ["uptime", "df -h", "free -h", "uname -a", "systemctl --failed --no-pager", "command -v docker >/dev/null && docker ps --format '{{.Names}}' || true"] }
pub fn summarize(_host:&SshHost, output:&str)->HealthInfo{ HealthInfo { uptime: output.lines().next().unwrap_or("unknown").into(), kernel: output.lines().find(|l|l.contains("Linux")).unwrap_or("unknown").into(), memory:"see free -h".into(), disk:"see df -h".into(), failed_services: output.matches("failed").count() as u32, docker_containers: output.lines().filter(|l|!l.trim().is_empty()).count() as u32 } }
